=== CaravanStudios/open-product-recovery/opr-models/src/offer.schema.json
{
  "$id": "offer.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Offer",
  "description": "An offer",
  "examples": [
    {
      "$ref": "exampleoffers/simpleoffer.json"
    }
  ],
  "additionalProperties": false,
  "properties": {
    "id": {
      "comment": "An identifier for this offer that is unique among all offers made by this organization.",
      "type": "string"
    },
    "description": {
      "comment": "The description of this offer as a whole",
      "type": "string"
    },
    "notes": {
      "comment": "Any human-readable notes for this offer",
      "type": "string"
    },
    "contents": {
      "comment": "The root product bundle describing the contents of this offer.",
      "$ref": "productbundle.schema.json"
    },
    "reshareChain": {
      "comment": "The reshare chain used to redeem friend-of-a-friend offers. Only present for reshared offers.",
      "$ref": "resharechain.schema.json"
    },
    "transportationDetails": {
      "comment": "Information about the offer's transportation",
      "$ref": "transportationdetails.schema.json"
    },
    "contactInfo": {
      "comment": "One or more people that can be contacted about this offer.",
      "oneOf": [
        {
          "$ref": "offercontact.schema.json"
        },
        {
          "type": "array",
          "item": {
            "$ref": "offercontact.schema.json"
          },
          "minItems": 1
        }
      ]
    },
    "offeredBy": {
      "type": "string",
      "format": "uri"
    },
    "offerLocation": {
      "$ref": "offerlocation.schema.json"
    },
    "offerExpirationUTC": {
      "comment": "The expiration time for this offer, expressed as a Unix timestamp in milliseconds since the epoch UTC",
      "$ref": "timestamp.schema.json"
    },
    "offerCreationUTC": {
      "comment": "The creation time for this offer, expressed as a Unix timestamp in milliseconds since the epoch UTC",
      "$ref": "timestamp.schema.json"
    },
    "offerUpdateUTC": {
      "comment": "The creation time for this offer, expressed as a Unix timestamp in milliseconds since the epoch UTC",
      "$ref": "timestamp.schema.json"
    },
    "maxReservationTimeSecs": {
      "comment" : "The maximum reservation time allowed for this offer, in seconds",
      "type" : "integer",
      "minimum" : 0
    }
  },
  "required": [
    "id",
    "description",
    "contents",
    "contactInfo",
    "offerLocation",
    "offerExpirationUTC",
    "offerCreationUTC"
  ],
  "type": "object"
}

=== CaravanStudios/open-product-recovery/components/models/src/exampleoffers/simpleoffer.json
{
  "id": "abc",
  "description": "A fake offer",
  "contents": {
    "contents": [
      {
        "description": "apple",
        "expirationTimestampUTC": 1663217495798,
        "id": "ceeb0a85-c5ab-4467-81b4-3ac1338b811a",
        "itemTypeIds": [
          {
            "itemId": "4145",
            "vocabularyId": "plu"
          }
        ],
        "price": {
          "currency": "USD",
          "value": 1.98
        },
        "quantity": 96
      }
    ],
    "description": "boxes of apples",
    "id": "f4ceefa5-d464-4fd1-bc77-99ceb66d2328",
    "isGrossEstimate": false,
    "packagingType": "box",
    "price": {
      "currency": "USD",
      "value": 1.98
    },
    "quantity": 10,
    "unitWeight": {
      "dimension": "weight",
      "unit": "pound",
      "value": 5
    }
  },
  "contactInfo": {
    "contactName": "Lone Star Dana",
    "contactEmail": "cowboyboots@citadelofdanas.org"
  },
  "offerLocation": {
    "locationName": "The Alamo",
    "locationAddress": "300 Alamo Plaza, San Antonio, TX 78205",
    "accessWindows": [
      {
        "startTimeUTC": 1,
        "endTimeUTC": 4000
      }
    ]
  },
  "offeredBy": "https://citadelofdanas.org/org.json",
  "offerExpirationUTC": 4000,
  "offerCreationUTC": 1
}
